name: hello-world-runner

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run a script
        run: echo 'Hello, world!'

      - name: Run multi-line script
        run: |
	  echo lmao1
	  echo lmao2
